- makesomo.sh
Gary - please check this & merge if ok.
I reused code from makeall.sh to expose parallelism for compiling us somo.
> expose parallel makes in makesomo.sh

- programs/us_convert/us_convert_gui.cpp
- programs/us_convert/us_convertio.cpp
- programs/us_convert/us_experiment.cpp
- programs/us_ramp/us_ramp_gui.cpp
- utils/us_analyte.cpp
- utils/us_db2.cpp
- utils/us_db2.h
- utils/us_model.cpp
- utils/us_noise.cpp
- utils/us_project.cpp
- utils/us_solution.cpp
Please review and if ok, I will merge to the main branch.
> fix for US_DB2::ERROR macro replacement -> US_DB2::DBERROR

- programs/us/us.cpp
- programs/us/us_win_data.cpp
- programs/us_pseudo_absorbance/add_refScan.cpp
- programs/us_pseudo_absorbance/add_refScan.h
- programs/us_pseudo_absorbance/build_colormap.cpp
- programs/us_pseudo_absorbance/build_colormap.h
- programs/us_pseudo_absorbance/convert_scan.cpp
- programs/us_pseudo_absorbance/convert_scan.h
- programs/us_pseudo_absorbance/refScan_dataIO.cpp
- programs/us_pseudo_absorbance/refScan_dataIO.h
- programs/us_pseudo_absorbance/select_program.cpp
- programs/us_pseudo_absorbance/select_program.h
- programs/us_pseudo_absorbance/switch.cpp
- programs/us_pseudo_absorbance/switch.h
- programs/us_pseudo_absorbance/us_pseudo_absorbance.pro
- programs/us_pseudo_absorbance/us_pseudo_absorbance_main.cpp
- first release of the pseudo-absorbance program
> first release of the pseudo-absorbance program

- programs/us_vhw_combine/us_vhw_combine.cpp
Modified checkbox text to distinguish between boundary fraction and concentration
> Changed text for switch for Boundary Fraction/Concentration

- programs/us_mpi_analysis/us_mpi_analysis.cpp
This was a local change present on demeler9 us3-nodb.
Should it be committed or removed?
> us_mpi_analysis.cpp - local change -IT on demeler9

- gui/us_plot.cpp
- gui/us_plot.h
- gui/us_widgets_dialog.cpp
- gui/us_widgets_dialog.h
- fixed the issue with changing the frame color
- save and load plot profiles to and from the json
> edit us_plot

- utils/us_astfem_math.cpp
Fix for https://github.com/ehb54/ultrascan-tickets/issues/158
@ehb54
> Fix bug exiting when simdatas last scan is matching to last experimental scan

- programs/us_convert/us_convert_gui.cpp
- programs/us_convert/us_convert_gui.h
- programs/us_convert/us_experiment.h
Hi Emre,
I didn't delete any lines of the us_convert. I just commented out those lines just in case there is a need to go back to the previous version quickly.
> New intensity to absorbance procedure in us_convert

- programs/us_convert/us_convert_gui.cpp
- programs/us_convert/us_convert_gui.h
…y user, then prepare list of reference triples for calculating the I_0 and pseudo-absorbance
> us_convert pseudo-absorbance correction

- .github/workflows/codeql-analysis.yml
- programs/us_reporter_gmp/us_reporter_gmp.cpp
Testing mod to fix codeQl compile failure
```
2023-10-23T21:38:11.1535215Z ../us_reporter_gmp/us_reporter_gmp.cpp:18:10: fatal error: ../us/us_revision.h: No such file or directory
2023-10-23T21:38:11.1537514Z    18 | #include "../us/us_revision.h"
2023-10-23T21:38:11.1539837Z       |          ^~~~~~~~~~~~~~~~~~~~~
2023-10-23T21:38:11.1541474Z compilation terminated.
```
> Update codeql-analysis.yml to fix issue with missing us/us_revision.h

- programs/us_pseudo3d_combine/us_pseudo3d_combine.cpp
> us_pseudo3d_combine.cpp : extended plot min/max range per BD

- programs/us/us.cpp
- programs/us/us.h
- utils/libus_utils.pro
- utils/us_geturl.cpp
- utils/us_geturl.h
Replace notices database with url
https://github.com/ehb54/ultrascan-tickets/issues/241
> Replace notices database with url

- utils/us_geturl.h
New class needed a US_UTIL_EXTERN for Windows compile https://github.com/ehb54/ultrascan-tickets/issues/261
> us_geturl.h : fix headers for linux compile

- gui/us_buffer_gui.cpp
> Update us_buffer_gui.cpp - spelling correction - issue #297

- programs/us_fematch/us_fematch.cpp
- programs/us_query_rmsd/us_query_rmsd.cpp
https://github.com/ehb54/ultrascan-tickets/issues/301
> Fix/Enhance us_query_rmsd

- gui/us_mwl_data.cpp
Fix for https://github.com/ehb54/ultrascan-tickets/issues/175
> Fix: IndexError us_edit Channels with different Wavelength #175

- programs/us_edit/us_edit.cpp
Additional properly reset whole window including airgap controls
https://github.com/ehb54/ultrascan-tickets/issues/256
> Fix: Axis label and plot title for mwl non RI/RA data #256

- programs/us_edit/us_edit.cpp
- programs/us_edit/us_select_lambdas.cpp
https://github.com/ehb54/ultrascan-tickets/issues/282
A lot of the lines changed could be condensed into changing us_mwl_data.cpp directly. but I wasn't sure if that would affect something else too
> Fix: Fix the sorting of wavelength in wavelength dropdowns #282

- programs/us_edit/us_edit.cpp
https://github.com/ehb54/ultrascan-tickets/issues/306
> Fix: Crash caused by wavelength controls

- programs/us_autoflow_analysis/us_autoflow_analysis.cpp
- programs/us_fematch/us_advanced_fem.cpp
- programs/us_fematch/us_advanced_fem.h
- programs/us_fematch/us_fematch.cpp
- programs/us_reporter_gmp/us_reporter_gmp.cpp
https://github.com/ehb54/ultrascan-tickets/issues/212
> Fix: Changing band volume in advanced dialog has no effect

- programs/us_edit/us_edit.cpp
addresses crash when attempting  manually editing a triple, and correct automated meniscus determination in the first place
> Alexey dev issue334: Editing stage failing, Pharmaron2

- gui/us_license.cpp
- gui/us_license.h
> 358 enhancement information needed to register ultrascan reduced to necessary ones

- programs/us_audit_trail_gmp/us_audit_trail_gmp.cpp
- programs/us_com_project/us_com_project_gui.cpp
- programs/us_com_project/us_com_project_gui.h
- programs/us_edit/us_edit.cpp
- programs/us_protocol_dev/us_protocol_dev_gui.cpp
- programs/us_protocol_dev/us_protocol_dev_gui.h
> Alexey dev issue365: When run defined as FAILED and reinitiated, submitter's info was missing in Report and audit trail

- .github/workflows/codeql-analysis.yml
- programs/us_2dsa/us_2dsa.cpp
- programs/us_autoflow_analysis/us_autoflow_analysis.cpp
- programs/us_convert/us_convert.cpp
- programs/us_convert/us_convert_gui.cpp
- programs/us_experiment/us_experiment_gui_optima.cpp
- programs/us_fematch/us_fematch.cpp
- programs/us_mpi_analysis/us_mpi_analysis.cpp
- programs/us_mwl_species_sim/us_mwl_species_sim.cpp
- programs/us_reporter_gmp/us_reporter_gmp.cpp
- utils/us_simparms.cpp
Fixing data corruption described in https://github.com/ehb54/ultrascan-tickets/issues/366 to avoid crashing programs like us_2dsa etc
> low acceleration rate conversion

- programs/us_convert/us_convert_gui.cpp
…tely when the wavelengths differ even if each channel has only one triple
> RIProfile issue with multi-wavelength runs

- programs/us_convert/us_convert_gui.cpp
- programs/us_convert/us_convert_gui.h
…discrepancy among triples and truncates all triples' scans to the minimum one.
> MW-AUC import causes crash #410

- gui/us_extinction_gui.cpp
Fixed text description for column header
> Updated the extinction column header to file name identifier

- gui/us_select_item.cpp
- gui/us_select_item.h
- programs/us_com_project/us_com_project_gui.cpp
- programs/us_com_project/us_com_project_gui.h
All actions are performed from the Run Manager
> Alexey dev issue414: Show actual instrument status uponn program launch, and also via 'Refresg Optima Status' button

- programs/us_config/us_database.cpp
- programs/us_config/us_database.h
This pull request includes several improvements and refactoring changes to the `US_Database` class in the `programs/us_config/us_database.cpp` file. The most important changes include adding validation for input fields, improving debug logging, and adding new functionality for parsing database URLs and handling clipboard operations.
* Added the `validate_value` method to validate input fields and provide visual feedback for missing values.
* Updated the `check_add` method to use `validate_value` for all input fields and display a consolidated error message.
* Introduced the `DbgLv` macro for conditional debug logging based on the debug level.
* Added debug logging statements in various methods to provide more detailed information during execution. …
> Enhance database setup GUI

- CITATION.cff
Addresses ticket #82  https://github.com/ehb54/ultrascan-tickets/issues/82
> Added CFF Citation file

- programs/us_2dsa/us_2dsa.cpp
> 2DSA GUI program. MC rmsd mismatch

- gui/us_select_item.cpp
to ease people's feeling :)...
> GMP / R&D Run Manager -- rename 'Delete Record' to 'Remove for the List' button

- admin/release/buildpkg.pl
- admin/release/redhat/Dockerfile
- admin/release/ubuntu/Dockerfile
- admin/release/ubuntu/mathops.h
- admin/release/ubuntu_qt6/Dockerfile
Updates to release build & dockerfiles
better manual building
utilization of qmake && make for faster ultrascan build
ubuntu 24 support
> Ehb issue 466

- programs/us_xpn_viewer/us_xpn_viewer_gui.cpp
…ima connection during various live update stages...
> GMP | R&D: 2. LIVE_UPDATE -- potential fixes for dropped usiab-to-optima
